table budgets
	lineageTag: abf09e68-6d36-4de2-b006-9c6230c0c5d9

	column parent_category
		dataType: string
		lineageTag: 51f9bce4-cd74-4dda-b256-df37e90c4959
		summarizeBy: none
		sourceColumn: parent_category

		annotation SummarizationSetBy = Automatic

	column yyyymm
		dataType: int64
		formatString: 0
		lineageTag: 35d85f5a-e9c9-4679-8dec-9ca38d4058d1
		summarizeBy: none
		sourceColumn: yyyymm

		annotation SummarizationSetBy = Automatic

	column budget_amount
		dataType: int64
		formatString: 0
		lineageTag: c7c309ba-7567-4a27-9a59-b3aef717d708
		summarizeBy: sum
		sourceColumn: budget_amount

		annotation SummarizationSetBy = Automatic

	partition budgets = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jo136\OneDrive\FinanceData\budgets\budgets.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"parent_category", type text}, {"yyyymm", Int64.Type}, {"budget_amount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

