table Measures_Main
	lineageTag: 617d435f-aedc-4e5d-b2b9-51256964853c

	measure 'Budget Amount' =
			
			SUM(budget_monthly[amount])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b14aea9f-d578-4bf1-a101-039212fc5dbe

	measure 'Actual Amount' =
			
			VAR amt = SUM(monthly_actuals_by_category[actual_signed])
			RETURN IF(SELECTEDVALUE(category_dim[top_bucket]) = "Income", amt, -amt)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 385ea110-5d91-4ebf-8450-5865a466aab6

	measure Variance = [Actual Amount] - [Budget Amount]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7b43ded1-2798-4947-ad33-03d115da4c31

	measure 'Variance %' = DIVIDE([Variance], [Budget Amount])
		lineageTag: 8ba8b32b-bfd7-4769-96d3-d9b940c260af

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CF Income' = SUM(monthly_cashflow[income])
		lineageTag: 1919880c-cc7c-4a25-8a6a-d13f5c85ac78

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CF Spending' = -SUM(monthly_cashflow[spending])
		lineageTag: ff58ba96-e79c-43ba-b61e-886e3705bf6c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CF Net' = SUM(monthly_cashflow[net_cashflow])
		lineageTag: e2518873-7bc7-4be3-ae02-bcf0ba400da2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NW Total' =
			
			IF(
			  HASONEVALUE('month_dim'[month]),
			  SUM(monthly_net_worth[net_worth]),
			  CALCULATE(SUM(monthly_net_worth[net_worth]), LASTDATE('month_dim'[month]))
			)
		lineageTag: 4c1aa16c-8fd0-4b80-886b-96ef0b0d29b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NW Assets' =
			
			IF(HASONEVALUE('month_dim'[month]),
			  SUM(monthly_net_worth[assets]),
			  CALCULATE(SUM(monthly_net_worth[assets]), LASTDATE('month_dim'[month]))
			)
		lineageTag: 622a3381-1d36-49a4-88c8-c62107e76fd1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NW Liabilities' =
			
			IF(HASONEVALUE('month_dim'[month]),
			  SUM(monthly_net_worth[liabilities]),
			  CALCULATE(SUM(monthly_net_worth[liabilities]), LASTDATE('month_dim'[month]))
			)
		lineageTag: 95322fc3-9beb-4380-9697-0499ffcc34f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NW Liquid' =
			
			IF(HASONEVALUE('month_dim'[month]),
			  SUM(monthly_net_worth[liquid_net_worth]),
			  CALCULATE(SUM(monthly_net_worth[liquid_net_worth]), LASTDATE('month_dim'[month]))
			)
		lineageTag: f1d57415-df3b-4d19-ada3-8ce3355ebfcb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NW Investable' =
			
			IF(HASONEVALUE('month_dim'[month]),
			  SUM(monthly_net_worth[investable_assets]),
			  CALCULATE(SUM(monthly_net_worth[investable_assets]), LASTDATE('month_dim'[month]))
			)
		lineageTag: e201518e-f973-4223-8e87-629628f531e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NW By Group (EOP)' =
			
			VAR LatestMonth = MAX('month_dim'[month])
			RETURN CALCULATE(SUM(monthly_net_worth_by_group[value]), 'month_dim'[month] = LatestMonth)
		lineageTag: 26969818-2935-4979-8d91-14ae3a5d71ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NW Group %' = DIVIDE([NW By Group (EOP)], [NW Total])
		lineageTag: a8a505f0-5093-4b65-bfd5-a1f2cf863808

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Portfolio Value' = ```
			
			CALCULATE(
			  SUM(monthly_allocation[value]),
			  ALLEXCEPT(monthly_allocation, monthly_allocation[month])
			)
			
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8b5a8cd6-1598-49d9-a889-a35b2345c84a

	measure 'Actual Weight' = ```
			
			DIVIDE(
			  SUM(monthly_allocation[value]),
			  [Portfolio Value]
			)
			
			```
		lineageTag: c0127e20-f434-4ce4-b9b9-03e0ad959cdb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Target Weight' = AVERAGE(allocation_vs_target[target_weight])
		lineageTag: 415ac29b-877b-41ce-be1a-03af4ef09fea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Variance Weight' = [Actual Weight] - [Target Weight]
		lineageTag: c750edd0-b2bb-4698-8ad9-e621480a441b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Value' =
			
			SUM(positions_enriched_export[value])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 794dcef8-09ac-4a05-9916-898fea4b15aa

	measure 'Portfolio Total (Selected)' =
			
			CALCULATE([Total Value], ALLSELECTED('security_dim'))
		lineageTag: a45a65dc-699e-4ce3-8841-fbd058d99cf4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% of Portfolio' =
			
			DIVIDE([Total Value], [Portfolio Total (Selected)])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c68d9077-a2b5-4263-9cde-01822ddb04a2

	measure 'Latest Month' =
			
			CALCULATE(MAX('month_dim'[month]), ALL('month_dim'))
		formatString: General Date
		lineageTag: 02c95118-b2c2-432e-a486-0480a408d5e8

	measure Amount_Total = ```
			
			SUM ( 'transactions_with_category'[amount] )
			
			Amount_avg_per_month =
			AVERAGEX (
			    VALUES ( 'calendar_dim'[yyyymm] ),   -- the months currently in filter
			    CALCULATE ( Amount_Total )          -- total for each month
			)
			
			```
		lineageTag: 2ce72292-0469-477d-9f09-11e7f602c387

	measure Trans_Amount_Total =
			
			SUM ( 'transactions_with_category'[amount] )
		lineageTag: e391dc71-41c1-48f1-a6ea-f9965d214777

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Trans_amount_month =
			
			AVERAGEX (
			    VALUES ( 'calendar_dim'[yyyymm] ),
			    CALCULATE ( [Trans_Amount_Total] )
			)
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		lineageTag: de2d972d-4ea0-4952-ae09-5da35f4672e9

	column Column1
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: db8b395b-7408-4703-bf41-a87dd22a80b7
		summarizeBy: sum
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Measures_Main = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlCKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

